### ISSUE TITLE
Question about logo

### ISSUE THREAD

**Issue by SomMeri** [less/less-meta#18]
Can I do make a logo for less4j that would be similar to less.js one? E.g. the one that would said `{less4j}` instead of `{less}`. I would probably change background color too (not sure yet), but kept the same gradient. If the answer is yes, what is the font name?

I am thinking about making a couple of stickers out of them so I can glue them around.

**Comment by seven-phases-max** [comment]
I'm not sure if anybody can recall who actually designed it. However from a common sense point of view it's under the same licences the https://github.com/less/less-docs is, so I don't see any (fair) reason why you could not do that.

We don't have any source code for it (just the png), but it should not be to difficult to replictate.

**Comment by matthew-dean** [comment]
Incidentally, if someone does make a nice vector that perfectly replicates the original logo, it would be great to keep that in a Less repo.

**Comment by matthew-dean** [comment]
I totally forgot to update this issue. Since we didn't have the original, I made a new logo when I started re-writing the 3.x docs. It's here - https://github.com/less/less-docs/tree/3.x/assets/logo

@SomMeri As far as making it look the same, I think if you can put the "4j" in a maybe a different color, that would be ideal. If it's all white lettering, I think it would be too easily confused with the Less logo.
